---
- name: Add repository
  yum_repository:
    name: epel
    description: EPEL YUM repo
    baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
    gpgkey: "https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}"

- name: Install common packages
  become: yes
  become_method: sudo
  yum:
    name: "{{ item.name }}"
    state: "{{ item.version | default('latest') }}"
  loop: "{{ common_pkgs }}"

- name: Install extra packages
  become: yes
  become_method: sudo
  yum:
    name: "{{ item.name }}"
    state: "{{ item.version | default('latest') }}"
  loop: "{{ extra_pkgs }}"
  when: extra_pkgs is defined
